# Generated by Django 4.0.5 on 2022-06-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria2',
            fields=[
                ('idCategoria2', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria2', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de usuario')),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Email')),
                ('Numero', models.CharField(max_length=11, verbose_name='Fono')),
                ('passs', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('categoria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
