# Generated by Django 4.0.5 on 2022-06-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria2_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Mascota'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, verbose_name='Tipo de mascota'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='categoria2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria2'),
        ),
    ]
