# Generated by Django 4.0.5 on 2022-06-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_id_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Numero',
            new_name='numero',
        ),
    ]
