# Generated by Django 4.0.5 on 2022-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Fono'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='passs',
            field=models.CharField(max_length=10, verbose_name='rut'),
        ),
    ]
