# Generated by Django 4.0.5 on 2022-06-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuarios_numero_alter_usuarios_passs'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=12, max_length=15, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
