# Generated by Django 4.0.5 on 2022-06-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=15, verbose_name='Precio del producto'),
        ),
    ]
