# Generated by Django 4.0.5 on 2022-06-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='dire',
            field=models.CharField(default=1, max_length=100, verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
