# Generated by Django 4.0.5 on 2022-11-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuarios_dire'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEquipoeInsumos',
            fields=[
                ('n_pabellon', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de pabellon')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de identificación')),
                ('equipo', models.CharField(max_length=300, verbose_name='Equipo que se solicita')),
                ('insumo', models.CharField(max_length=300, verbose_name='Insumos que se solicita')),
                ('msg', models.CharField(max_length=300, verbose_name='Comentario Adicional')),
            ],
        ),
    ]
