# Generated by Django 4.0.5 on 2022-11-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solicitudequipoeinsumos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria3',
            fields=[
                ('id_condicion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Condicion')),
                ('nombre_condicion', models.CharField(max_length=50, verbose_name='Condicion Si o No')),
            ],
        ),
        migrations.CreateModel(
            name='PabellonEnCondiciones',
            fields=[
                ('n_pabellon', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Numero de pabellon')),
                ('msg', models.CharField(max_length=300, verbose_name='Comentario adicional')),
                ('c_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria2')),
                ('c_infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('c_rrhh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria3')),
            ],
        ),
    ]
